require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - config/**/*.rb

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
