require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - config/**/*.rb
    - db/**/*.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/api/**/*.rb

RSpec/ContextWording:
  Exclude:
    - spec/api/**/*.rb

RSpec/MultipleExpectations:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 12
