* Weather API
** Tasks
   - [X] Разобрать ТЗ
   - [X] Accuweather
     - [X] Apikey
     - [X] Client
     - [X] Update interactor
   - [X] Rails
   - [X] RSpec
   - [X] RSwag
   - [X] Grape
   - [X] /health
   - [X] VCR
   - [X] Rufus
   - [X] /weather
     - [X] /current
     - [X] /historical
       - [X] /
       - [X] /max
       - [X] /min
       - [X] /avg
     - [X] /by_time
   - [X] Cover with specs
     - [X] /weather
       - [X] /current
       - [X] /by_time
       - [X] /historical
         - [X] /
         - [X] /max
         - [X] /min
         - [X] /avg
   - [ ] SimpleCov
** ТЗ
   #+begin_example
Тестовое задание: API для статистики по погоде
Как источник данных можно использовать https://developer.accuweather.com/apis.
Город можно использовать любой (можно захардкодить).
Законченный код передать в виде приватного репозитория на GitHub (Доступ можно выдать https://github.com/AgriasDev)
API открыт для всех, авторизация не нужна.
Ожидаемая нагрузка на любой эндпоинт: 5 RPS

Необходимые эндпоинты:

/weather/current - Текущая температура
/weather/historical - Почасовая температура за последние 24 часа (https://developer.accuweather.com/accuweather-current-conditions-api/apis/get/currentconditions/v1/%7BlocationKey%7D/historical/24)
/weather/historical/max - Максимальная темперетура за 24 часа
/weather/historical/min - Минимальная темперетура за 24 часа
/weather/historical/avg - Средняя темперетура за 24 часа
/weather/by_time - Найти температуру ближайшую к переданному timestamp (например 1621823790 должен отдать температуру за 2021-05-24 08:00. Из имеющихся данных, если такого времени нет вернуть 404)
/health - Статус бекенда (Можно всегда отвечать OK)

Должны быть интеграционные тесты на эндпоинты и юнит тесты на общие классы/модули.
Рекомендуется хранить данные о температуре локально для снижения нагрузки на сторонний API.
Рекомендуется использовать библиотеки: Rails 6+, Grape, Delayed::Job, Rufus, RSpec, VCR.
Приветствуется использование кеширования и Trailblazer, swagger документации, Docker
   #+end_example
** 09/11/2022
*** 14:14:45
    Создать репозиторий.
*** 14:29:33
    Есть accuweather gem, можно пользоваться?

    Нет возможности получать historical запрос за 24 часа.

    Создать аккаунт, для Apikey.
*** 15:14:33
    Получен.

    Теперь Rails.
*** 16:27:16
    Из того что рекомендуется и приветствуется, сходу непонятен только Trailblazer.

    Тогда дальше пожалуй RSpec и RSwag.
*** 22:48:30
    Сделать /health на Grape.
** 10/11/2022
*** 12:03:34
    AccuweatherClient
*** 16:28:33
    UpdateAccuweatherData interactor

    Сначала AccuweatherData.
*** 19:58:23
    Коммит. И добавить планировщик.
** 11/11/2022
*** 11:43:51
    Исправить ошибки запросов к Accuweather.
*** 14:03:03
    /weather
*** 16:07:58
    Покрыть тестами.
*** 20:02:30
    Может ещё SimpleCov?
